// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: checker/v1/checker.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// CheckURL request
type CheckURLRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MonitorId     string                 `protobuf:"bytes,1,opt,name=monitor_id,json=monitorId,proto3" json:"monitor_id,omitempty"`
	Url           string                 `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckURLRequest) Reset() {
	*x = CheckURLRequest{}
	mi := &file_checker_v1_checker_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckURLRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckURLRequest) ProtoMessage() {}

func (x *CheckURLRequest) ProtoReflect() protoreflect.Message {
	mi := &file_checker_v1_checker_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckURLRequest.ProtoReflect.Descriptor instead.
func (*CheckURLRequest) Descriptor() ([]byte, []int) {
	return file_checker_v1_checker_proto_rawDescGZIP(), []int{0}
}

func (x *CheckURLRequest) GetMonitorId() string {
	if x != nil {
		return x.MonitorId
	}
	return ""
}

func (x *CheckURLRequest) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

// CheckURL response
type CheckURLResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	MonitorId      string                 `protobuf:"bytes,1,opt,name=monitor_id,json=monitorId,proto3" json:"monitor_id,omitempty"`
	Status         string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"` // UP / DOWN
	ResponseTimeMs int64                  `protobuf:"varint,3,opt,name=response_time_ms,json=responseTimeMs,proto3" json:"response_time_ms,omitempty"`
	CheckedAt      int64                  `protobuf:"varint,4,opt,name=checked_at,json=checkedAt,proto3" json:"checked_at,omitempty"` // unix timestamp
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CheckURLResponse) Reset() {
	*x = CheckURLResponse{}
	mi := &file_checker_v1_checker_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckURLResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckURLResponse) ProtoMessage() {}

func (x *CheckURLResponse) ProtoReflect() protoreflect.Message {
	mi := &file_checker_v1_checker_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckURLResponse.ProtoReflect.Descriptor instead.
func (*CheckURLResponse) Descriptor() ([]byte, []int) {
	return file_checker_v1_checker_proto_rawDescGZIP(), []int{1}
}

func (x *CheckURLResponse) GetMonitorId() string {
	if x != nil {
		return x.MonitorId
	}
	return ""
}

func (x *CheckURLResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *CheckURLResponse) GetResponseTimeMs() int64 {
	if x != nil {
		return x.ResponseTimeMs
	}
	return 0
}

func (x *CheckURLResponse) GetCheckedAt() int64 {
	if x != nil {
		return x.CheckedAt
	}
	return 0
}

var File_checker_v1_checker_proto protoreflect.FileDescriptor

const file_checker_v1_checker_proto_rawDesc = "" +
	"\n" +
	"\x18checker/v1/checker.proto\x12\n" +
	"checker.v1\"B\n" +
	"\x0fCheckURLRequest\x12\x1d\n" +
	"\n" +
	"monitor_id\x18\x01 \x01(\tR\tmonitorId\x12\x10\n" +
	"\x03url\x18\x02 \x01(\tR\x03url\"\x92\x01\n" +
	"\x10CheckURLResponse\x12\x1d\n" +
	"\n" +
	"monitor_id\x18\x01 \x01(\tR\tmonitorId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12(\n" +
	"\x10response_time_ms\x18\x03 \x01(\x03R\x0eresponseTimeMs\x12\x1d\n" +
	"\n" +
	"checked_at\x18\x04 \x01(\x03R\tcheckedAt2W\n" +
	"\x0eCheckerService\x12E\n" +
	"\bCheckURL\x12\x1b.checker.v1.CheckURLRequest\x1a\x1c.checker.v1.CheckURLResponseB2Z0github.com/impruthvi/pulse-check-apis/checker/v1b\x06proto3"

var (
	file_checker_v1_checker_proto_rawDescOnce sync.Once
	file_checker_v1_checker_proto_rawDescData []byte
)

func file_checker_v1_checker_proto_rawDescGZIP() []byte {
	file_checker_v1_checker_proto_rawDescOnce.Do(func() {
		file_checker_v1_checker_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_checker_v1_checker_proto_rawDesc), len(file_checker_v1_checker_proto_rawDesc)))
	})
	return file_checker_v1_checker_proto_rawDescData
}

var file_checker_v1_checker_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_checker_v1_checker_proto_goTypes = []any{
	(*CheckURLRequest)(nil),  // 0: checker.v1.CheckURLRequest
	(*CheckURLResponse)(nil), // 1: checker.v1.CheckURLResponse
}
var file_checker_v1_checker_proto_depIdxs = []int32{
	0, // 0: checker.v1.CheckerService.CheckURL:input_type -> checker.v1.CheckURLRequest
	1, // 1: checker.v1.CheckerService.CheckURL:output_type -> checker.v1.CheckURLResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_checker_v1_checker_proto_init() }
func file_checker_v1_checker_proto_init() {
	if File_checker_v1_checker_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_checker_v1_checker_proto_rawDesc), len(file_checker_v1_checker_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_checker_v1_checker_proto_goTypes,
		DependencyIndexes: file_checker_v1_checker_proto_depIdxs,
		MessageInfos:      file_checker_v1_checker_proto_msgTypes,
	}.Build()
	File_checker_v1_checker_proto = out.File
	file_checker_v1_checker_proto_goTypes = nil
	file_checker_v1_checker_proto_depIdxs = nil
}
