// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: monitor/v1/monitor.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Monitor model
type Monitor struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Url             string                 `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	IntervalSeconds int32                  `protobuf:"varint,3,opt,name=interval_seconds,json=intervalSeconds,proto3" json:"interval_seconds,omitempty"`
	Status          string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`                                       // UP / DOWN
	LastCheckedAt   int64                  `protobuf:"varint,5,opt,name=last_checked_at,json=lastCheckedAt,proto3" json:"last_checked_at,omitempty"` // unix timestamp
	ResponseTimeMs  int64                  `protobuf:"varint,6,opt,name=response_time_ms,json=responseTimeMs,proto3" json:"response_time_ms,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Monitor) Reset() {
	*x = Monitor{}
	mi := &file_monitor_v1_monitor_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Monitor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Monitor) ProtoMessage() {}

func (x *Monitor) ProtoReflect() protoreflect.Message {
	mi := &file_monitor_v1_monitor_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Monitor.ProtoReflect.Descriptor instead.
func (*Monitor) Descriptor() ([]byte, []int) {
	return file_monitor_v1_monitor_proto_rawDescGZIP(), []int{0}
}

func (x *Monitor) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Monitor) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *Monitor) GetIntervalSeconds() int32 {
	if x != nil {
		return x.IntervalSeconds
	}
	return 0
}

func (x *Monitor) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Monitor) GetLastCheckedAt() int64 {
	if x != nil {
		return x.LastCheckedAt
	}
	return 0
}

func (x *Monitor) GetResponseTimeMs() int64 {
	if x != nil {
		return x.ResponseTimeMs
	}
	return 0
}

// CreateMonitor request API
type CreateMonitorRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Url             string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	IntervalSeconds int32                  `protobuf:"varint,2,opt,name=interval_seconds,json=intervalSeconds,proto3" json:"interval_seconds,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CreateMonitorRequest) Reset() {
	*x = CreateMonitorRequest{}
	mi := &file_monitor_v1_monitor_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateMonitorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateMonitorRequest) ProtoMessage() {}

func (x *CreateMonitorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_monitor_v1_monitor_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateMonitorRequest.ProtoReflect.Descriptor instead.
func (*CreateMonitorRequest) Descriptor() ([]byte, []int) {
	return file_monitor_v1_monitor_proto_rawDescGZIP(), []int{1}
}

func (x *CreateMonitorRequest) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *CreateMonitorRequest) GetIntervalSeconds() int32 {
	if x != nil {
		return x.IntervalSeconds
	}
	return 0
}

// CreateMonitor response API
type CreateMonitorResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Monitor       *Monitor               `protobuf:"bytes,1,opt,name=monitor,proto3" json:"monitor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateMonitorResponse) Reset() {
	*x = CreateMonitorResponse{}
	mi := &file_monitor_v1_monitor_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateMonitorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateMonitorResponse) ProtoMessage() {}

func (x *CreateMonitorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_monitor_v1_monitor_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateMonitorResponse.ProtoReflect.Descriptor instead.
func (*CreateMonitorResponse) Descriptor() ([]byte, []int) {
	return file_monitor_v1_monitor_proto_rawDescGZIP(), []int{2}
}

func (x *CreateMonitorResponse) GetMonitor() *Monitor {
	if x != nil {
		return x.Monitor
	}
	return nil
}

// GetMonitor request API
type GetMonitorRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMonitorRequest) Reset() {
	*x = GetMonitorRequest{}
	mi := &file_monitor_v1_monitor_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMonitorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMonitorRequest) ProtoMessage() {}

func (x *GetMonitorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_monitor_v1_monitor_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMonitorRequest.ProtoReflect.Descriptor instead.
func (*GetMonitorRequest) Descriptor() ([]byte, []int) {
	return file_monitor_v1_monitor_proto_rawDescGZIP(), []int{3}
}

func (x *GetMonitorRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// GetMonitor response API
type GetMonitorResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Monitor       *Monitor               `protobuf:"bytes,1,opt,name=monitor,proto3" json:"monitor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMonitorResponse) Reset() {
	*x = GetMonitorResponse{}
	mi := &file_monitor_v1_monitor_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMonitorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMonitorResponse) ProtoMessage() {}

func (x *GetMonitorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_monitor_v1_monitor_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMonitorResponse.ProtoReflect.Descriptor instead.
func (*GetMonitorResponse) Descriptor() ([]byte, []int) {
	return file_monitor_v1_monitor_proto_rawDescGZIP(), []int{4}
}

func (x *GetMonitorResponse) GetMonitor() *Monitor {
	if x != nil {
		return x.Monitor
	}
	return nil
}

var File_monitor_v1_monitor_proto protoreflect.FileDescriptor

const file_monitor_v1_monitor_proto_rawDesc = "" +
	"\n" +
	"\x18monitor/v1/monitor.proto\x12\n" +
	"monitor.v1\"\xc0\x01\n" +
	"\aMonitor\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x10\n" +
	"\x03url\x18\x02 \x01(\tR\x03url\x12)\n" +
	"\x10interval_seconds\x18\x03 \x01(\x05R\x0fintervalSeconds\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x12&\n" +
	"\x0flast_checked_at\x18\x05 \x01(\x03R\rlastCheckedAt\x12(\n" +
	"\x10response_time_ms\x18\x06 \x01(\x03R\x0eresponseTimeMs\"S\n" +
	"\x14CreateMonitorRequest\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\x12)\n" +
	"\x10interval_seconds\x18\x02 \x01(\x05R\x0fintervalSeconds\"F\n" +
	"\x15CreateMonitorResponse\x12-\n" +
	"\amonitor\x18\x01 \x01(\v2\x13.monitor.v1.MonitorR\amonitor\"#\n" +
	"\x11GetMonitorRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"C\n" +
	"\x12GetMonitorResponse\x12-\n" +
	"\amonitor\x18\x01 \x01(\v2\x13.monitor.v1.MonitorR\amonitor2\xb3\x01\n" +
	"\x0eMonitorService\x12T\n" +
	"\rCreateMonitor\x12 .monitor.v1.CreateMonitorRequest\x1a!.monitor.v1.CreateMonitorResponse\x12K\n" +
	"\n" +
	"GetMonitor\x12\x1d.monitor.v1.GetMonitorRequest\x1a\x1e.monitor.v1.GetMonitorResponseB2Z0github.com/impruthvi/pulse-check-apis/monitor/v1b\x06proto3"

var (
	file_monitor_v1_monitor_proto_rawDescOnce sync.Once
	file_monitor_v1_monitor_proto_rawDescData []byte
)

func file_monitor_v1_monitor_proto_rawDescGZIP() []byte {
	file_monitor_v1_monitor_proto_rawDescOnce.Do(func() {
		file_monitor_v1_monitor_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_monitor_v1_monitor_proto_rawDesc), len(file_monitor_v1_monitor_proto_rawDesc)))
	})
	return file_monitor_v1_monitor_proto_rawDescData
}

var file_monitor_v1_monitor_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_monitor_v1_monitor_proto_goTypes = []any{
	(*Monitor)(nil),               // 0: monitor.v1.Monitor
	(*CreateMonitorRequest)(nil),  // 1: monitor.v1.CreateMonitorRequest
	(*CreateMonitorResponse)(nil), // 2: monitor.v1.CreateMonitorResponse
	(*GetMonitorRequest)(nil),     // 3: monitor.v1.GetMonitorRequest
	(*GetMonitorResponse)(nil),    // 4: monitor.v1.GetMonitorResponse
}
var file_monitor_v1_monitor_proto_depIdxs = []int32{
	0, // 0: monitor.v1.CreateMonitorResponse.monitor:type_name -> monitor.v1.Monitor
	0, // 1: monitor.v1.GetMonitorResponse.monitor:type_name -> monitor.v1.Monitor
	1, // 2: monitor.v1.MonitorService.CreateMonitor:input_type -> monitor.v1.CreateMonitorRequest
	3, // 3: monitor.v1.MonitorService.GetMonitor:input_type -> monitor.v1.GetMonitorRequest
	2, // 4: monitor.v1.MonitorService.CreateMonitor:output_type -> monitor.v1.CreateMonitorResponse
	4, // 5: monitor.v1.MonitorService.GetMonitor:output_type -> monitor.v1.GetMonitorResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_monitor_v1_monitor_proto_init() }
func file_monitor_v1_monitor_proto_init() {
	if File_monitor_v1_monitor_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_monitor_v1_monitor_proto_rawDesc), len(file_monitor_v1_monitor_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_monitor_v1_monitor_proto_goTypes,
		DependencyIndexes: file_monitor_v1_monitor_proto_depIdxs,
		MessageInfos:      file_monitor_v1_monitor_proto_msgTypes,
	}.Build()
	File_monitor_v1_monitor_proto = out.File
	file_monitor_v1_monitor_proto_goTypes = nil
	file_monitor_v1_monitor_proto_depIdxs = nil
}
